[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.pdo",
  "php83Extensions.pdo_sqlite",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.tokenizer",
  "php83Extensions.xml",
  "php83Extensions.ctype",
  "php83Extensions.fileinfo",
  "composer"
]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan migrate --force --no-interaction; sleep 2 && php artisan serve --host=0.0.0.0 --port=$PORT"